version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./Docker_mysql.file
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  test-db:
    build:
      context: .
      dockerfile: ./Docker_test_db.file
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
  web:
    build:
      context: .
      dockerfile: Docker.file
    command: /bin/sh -c "rm -f /smart_stylist/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - test-db
    ports:
      - "3000:3000"
    volumes:
      - .:/smart_stylist