default: &default
  adapter: mysql2
  charset: utf8
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  timeout: 5000

development:
  <<: *default
  database: smart_stylist_development_mysql2
  username: root
  host: db


test:
  <<: *default
  database: smart_stylist_test_mysql2

production:
  <<: *default
  port: <%= ENV['RDS_PORT'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>

